language: python

python:
    - 3.5
    - 3.5-dev
    - nightly

install:
    - pip install -r requirements.txt
    - pip install -r requirements-test.txt
    - pip install coveralls

script:
#    - py.test
    - coverage run --source=wglib setup.py test
    
after_success:
    - coveralls